from constants import MESSAGEM_ERRO_NUMERO_NAO_INTEIRO, ERRO, MESSAGEM_ERRO_FORA_DO_LIMITE

NAO_INTEIRO = {ERRO: MESSAGEM_ERRO_NUMERO_NAO_INTEIRO}
FORA_DO_LIMITE = {ERRO: MESSAGEM_ERRO_FORA_DO_LIMITE}


